jni/Application.mk

Will not compile with clang, so toolchain override must remain.

Allow compiling android jni for all archs

---

libretro.c

gpSP is missing L and R descriptors as shown here.
https://github.com/libretro/gpsp/blob/434612ab6824bca0d3e88d0b7135b8a9ffc12061/libretro.c#L408-L418
https://github.com/libretro/gpsp/blob/434612ab6824bca0d3e88d0b7135b8a9ffc12061/input.h#L46-L57
This commit adds the missing L and R descriptors.
Compiled and tested successfully on Windows 10 x64.

Update libretro.c: Add missing input descriptors

---

Makefile
libco/libco.c
libco/psp1.c

Since this core was originally an emulator for the PSP, it seems only fitting to get it working for the PSP again :)
First of all, it needed a PSP implementation of libco.
Secondly, it needed the path to the headers from the PSP SDK.
As always, this is way out of my area of expertise so please feel free to modify the code as needed.
The core is still too slow to be playable on the PSP, but one thing at a time...
Thanks!

Fix compilation for PSP

---

libretro.c
main.h
video.c

gpSP and most of its forks for the PSP require frame skipping in order to play many games without audio stuttering.
I haven't been happy with my various attempts to add auto frame skipping so far, but I figured I could at least add manual frame skipping for now.
This also fixes a small dynarec bug related to ram_translation_cache.

Add manual frame skipping

---

3ds/3ds_cache_utils.S
3ds/3ds_utils.c
3ds/3ds_utils.h
Makefile
libretro.c

Similar fix to https://github.com/libretro/pcsx_rearmed/pull/390. The Nintendo svcBackdoor can cause stack corruption if an interrupt happens during it, this uses Luma3DS/Rosalina's svcCustomBackdoor instead.
With this patch, I haven't experienced any ingame crashes. However, when switching between games, there are still user-mode data aborts in the dynarec. This patch should still improve stability quite a bit.

[3DS] Fix dynarec prefetch aborts

---

libretro.c

- This fixes erroneous achievement being rewarded.
- This implements retro_memory_map/descriptors for better memory maps. (this is in response to an upcoming PR : https://github.com/libretro/RetroArch/pull/10397/files). This PR should still work even without that PR merged.

Fix cheevos support

---

3ds/3ds_utils.c
3ds/3ds_utils.h

This avoids an error when building under GCC 10, and should not affect earlier versions.

[3DS] Move has_rosalina to avoid duplicate definitions

---

gba_memory.c

- Based on notes, gpSP's RTC does was based on vba.
- I've updated relevant sections of it based on latest vba.
reference issue: https://github.com/libretro/gpsp/issues/79

Update RTC emulation

---

Makefile
Makefile.common
libretro.c
retro_emu_thread.c
retro_emu_thread.h

At present, the emulation code of gpSP is wrapped with libco. This PR adds a new compile-time option (`USE_LIBCO`) which can be disabled to instead use a pthreads-based mechanism.
Why would we want such a thing?
1) libco is fine, but can cause strange and unpredictable behaviour when used with code not specifically designed around it
2) We simply don't have working libco implementations for all platforms. A notable example is OpenDingux - attempting to use libco on OpenDingux causes the instant death of the process...
From basic testing using RetroArch's fast forward feature, I see a performance decrease when using the pthreads-based mechanism of ~7%. `USE_LIBCO` is therefore set to `1` on *all* platforms apart from OpenDingux, where it is absolutely required.
I should make it very clear …

Add build-time option to run the emulator in a thread instead of libco (fixes OpenDingux target)

---

arm/arm_emit.h
cpu_threaded.c

Turns out there were a couple of very interesting and hard to track
bugs. A missing comma made the reg list too short, leaving the 31th
element at the mercy of the linker ordering algorithm, which seems to
work in some cases depending on the compiler version.
Also the cache flush code seemed not to work on my machine (OGA),
not sure why it wored in the past :/

Fix ARM dynarec

---

gba_memory.c
sound.c

This causes crashes in PSP quite often in many games. Other CPUs might
(depending on the processor state) silently return zero or some
undefined value.
The fix is borrowed from ReGBA's codebase

Small fixes to division by zero

---

arm/arm_stub.S

This gets rid of stack usage (except for callback invocations) in the
dynarec execution code. A requirement to make the dynarec re-entrant.

Minor improvements in ARM stubs

---

arm/arm_stub.S

Fix a C func call while at it. This is a prerequisite to make the
dynarec re-entrant and get rid of libco

ARM dynarec: Do not use the stack at all

---

Makefile
common.h
cpu.h
cpu_threaded.c
gba_memory.c
gba_memory.h
x86/x86_emit.h

The dynarec expects function args to be located in registers instead of
the stack, which is not the default calling convetion in GCC/clang.

Fix x86 dynarec, broken by d10c4afe

---

psp/mips_stub.S

Affects at least SM Adv 4 on PSP, which doesn't load at all.
I think the MIPS pipeline does not like invalidating the Icache and
using it immediately after (seems to read an old value sometimes?).
Rewired it to not do that and instead jump to the handler directly.

Fix a ghost bug with some games

---

common.h
cpu_threaded.c
gba_memory.c
main.c
main.h

This is unnecessary since newlib supports all file I/O.
This is needed for other mips ports

Remove PSP-specific stuff from MIPS backend

---

arm/arm_stub.S
cpu.c
gba_memory.c
psp/mips_stub.S
x86/x86_stub.S

Will move also OAM structures to gain a few cycles per load/store.
Loads can also be optimized for an extra instruction per access.

Move palettes around to simplify MIPS dynarec

---

arm/arm_stub.S
cpu.c
psp/mips_stub.S
x86/x86_stub.S

This gets rid of some more absolute addrs in the MIPS dynarec.
Tested on several platforms, we should be good.

Move a few more registers to context

---

libretro.c

At present, the second time that content is loaded with the core on dynamic platforms, the `Color Correction` and `Interframe Blending` options are ignored (i.e. they are always set to disabled). This is a previously hidden bug (which should never occur on dynamic platforms...), and it seems to be platform-dependent: the core has always functioned correctly in the past, and it still functions correctly on half my devices. It is likely that an OS (glibc) update has revealed the underlying issue...
This PR simply ensures that the video post processing configuration is properly reset inside retro_deinit(). This 'forces' correct initialisation each time the core is loaded.

Ensure post processing configuration is correctly reset in retro_deinit()

---

arm/arm_stub.S
cpu.c
cpu.h
cpu_threaded.c
gba_memory.c
gba_memory.h
libretro.c
main.c

This is not really necessary since it can share area with ROM.
Performance impact should be very minimal (haven't noticed it myself)
and could be compensated (even by a positive offset) if we bump the ROM
cache area size.
Tested with several dynarecs.

Remove BIOS reserved translation area

---

arm/arm_stub.S
x86/x86_stub.S

Still does not solve the issue of nested C functions but that will need more work to fix.
Also there's an issue with gcc and clang using different instruction namings (ldrbne vs ldrneb), will look into it once we resolve the C issues though.

asm fixes for clang

---

common.h
cpu.h
cpu_threaded.c
gba_memory.c
libretro.c
libretro_core_options.h
main.c
x86/x86_stub.S

Added a more thorough cache cleanup for reset/mode-change too.
Fixed the mmap initialization that ends up leaking memory.
Minor x86 asm fixes for Android.

Enable runtime dynarec enable/disable

---

arm/arm_stub.S
cpu.c
cpu.h
cpu_threaded.c
gba_memory.c
gba_memory.h
libretro.c
psp/mips_emit.h
psp/mips_stub.S
x86/x86_emit.h
x86/x86_stub.S

This saves a few cycles in MIPS and simplifies a bit the core.
Removed the write map, only affects interpreter performance very
minimally. Rewired ARM and x86 handlers to support direct access to
I/EWRAM (and VRAM on ARM) to compensate. Overall performance is slightly
better but code is cleaner and allows for further improvements in the
dynarecs.

Make ewram memory linear

---

arm/arm_stub.S
cpu.h
cpu_threaded.c
gpsp_config.h
psp/mips_emit.h
psp/mips_stub.S
x86/x86_stub.S

Seems that using the __atribute__ magic for sections is not the best way
of doing this, since it injects some default atributtes that collide
with the user defined ones. Using assembly is far easier in this case.
Reworked definitions a bit to make it easier to import from assembly.
Also wrapped stuff around macros for easy and less verbose
implementation of the symbol prefix issue.

Move caches to stub files to get around gcc 10

---

.gitlab-ci.yml
Makefile

This PR fixes the OpenDingux Beta build.
Apparently the ASM code and/or MIPS dynarec does not respect MIPS calling conventions, so the core will crash on load under OpenDingux Beta unless it is compiled with the `-fno-caller-saves` flag.

Fix OpenDingux Beta build

---

arm/arm_emit.h
arm/arm_stub.S

Using an invalid SP makes Vita crash (for an unkown reason) and makes
things like C signal handlers crash (luckily Retroarch doesn't use
them). It is also a violation of the ABI and not a great idea.
Recycled some little used registers to free SP. Perf should be roughly
the same.

Fix Vita port and likely some Linux/Android hidden issues

---

cpu.c

An address check was missing to read aligned 32 (stm/ldm) data from
high mem areas (0xX0000000). This fixes SM4 EU that for some reason has
some weird memory access (perhaps a bug?)

Fix aligned32 reads in interpreter mode

---

input.c
input.h
libretro.c
libretro.h

This PR uses the new `RETRO_ENVIRONMENT_SET_FASTFORWARDING_OVERRIDE` environment callback (https://github.com/libretro/RetroArch/pull/11547) to add a dedicated 'hold to fast forward' button, mapped to RetroPad `R2` by default. This serves as a reference implementation for other core devs.
Q) Why would we want a dedicated fast-forward button, when RetroArch already has this functionality via hotkeys?
A) Hotkeys are, by and large, inconvenient when the user only has a gamepad for input. Due to the fact that most gamepads only have the bare minimum of buttons, enabling fast-forward via hotkeys requires the use of both a hotkey enable button and the fast-forward button itself - so two inputs must be pressed simultaneously. Attempting to set up a 'hold to fast forward' hotkey combo in this …

Add dedicated RetroPad fast-forward button

---

libretro/libretro.c
sound.c
sound.h

At present, the core is susceptible to crackling audio, particularly when using low frontend audio latency settings.
This is because the core is handling audio output suboptimally. At the set audio sample rate, the frontend expects between 1097 and 1098 audio samples per frame - but the core is sending samples in multiples of 256. This means that the audio output becomes 'desynchronised' with retro_run() - sometimes 1024 samples will get sent to the frontend for the current frame, sometimes 1280 as the core either falls behind or overcompensates. As a result, when the frontend tries to synchronise on audio, jitter can occur - and if the frontend audio buffer is small (when using low latency values), it can sometimes run dry or reach capacity, causing crackling.
This PR modifies audio …

Send audio samples to frontend with correct pacing

---

Makefile

As this platform only has 32MB RAM.

platforms/miyoo: Use small translation cache

---

gba_over.h

Wrong Gamepak Code causing Pokemon Fire Red not to boot due to wrong flash size (64k instead of 128k)
German version of Pokemon Leaf works beautifully...
In "game_config.txt" the gamepak code is correct. However, Firered German Version still will not boot.
Changing Header of the Rom to wrong (and not official) Gamepak "BPRG", the Game will boot.
I think the "game_config.txt" will not be used and the settings are hardcoded to the build, correct?
Please pull the change.
Thanks!

Pokemon Fire Red germany not booting/ White Screen

---

libretro/libretro.c

VFS callbacks fail since it requires V2, which includes vfs_truncate. Otherwise it falls back to libretro-common code. Current VFS wrapping code in libretro-common needs V2 since vfs_truncate's callback is set.
https://github.com/libretro/libretro-common/blob/master/streams/file_stream.c#L65
Now VFS callbacks work properly in frontends that support them. Otherwise a hack of setting "cb->required_interface_version = 2" in frontend works. Only cores, according to specs, are meant to set the required version.

Use proper VFS version.

---

video.c

Noticed that an issue with Rayman 3 Hoodlum Havoc was reported on one of the gpsp compatability lists.  Cross-checked against mgba and revealed the same issue reported as being present in an earlier version -
https://github.com/mgba-emu/mgba/issues/377
This PR applies the same fix as used in mgba.  Could affect other games also.

Don't update background scanline params in mode 0

---

libretro/libretro.c

As requested in issue #37 .  Could probably lose the 'v0.91' from the build version as well and just have it report the github build.

Add u1 extension to supported filetypes

---

Makefile

Currently, the 60 FPS overclock hack is only limited to PSVita.
But i think some other platforms can take advantage of the 60 FPS overclock.
What i did is add in the Makefile the ability of using the additional argument **OVERCLOCK_60FPS=1** for build (compile) gpSP with the 60FPS overclock hack for any platform.
To compile using the 60FPS overclock hack, run **make OVERCLOCK_60FPS=1**

allow passing additional argument for compile gpSP with 60FPS overclock for any platform
